### ISSUE TITLE
conda-forge/neptune-client-feedstock stopped automerging without an apparent reason

### ISSUE THREAD

**Issue by PiotrJander** [conda-forge/conda-feedstock#142]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I am one of the maintainers of https://github.com/conda-forge/neptune-client-feedstock 

Recently, as we bumped the version of neptune-client on PyPI from 0.5.x to 0.9.0, conda-forge bot stopped automerging new versions and publishing them on conda. We have had to publish those new version by making manual changes to https://github.com/conda-forge/neptune-client-feedstock .

Is this a problem with conda forge automerging mechanism or something we are missing as maintainers?

I am happy to provide more details, but not sure what info is relevant.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
N/A
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
N/A
```
</details>

**Comment by ocefpaf** [comment]
Hi @PiotrJander, this is the conda package feedstock and the bot team won't see this issue here. You can open an issue in your feedstock and bump the team with `@conda-forge/bot`.

Also, if you go to https://conda-forge.org/status/#version_updates and search for your package you'll probably see a log of the bot error.
