### ISSUE TITLE
This package is quite large.....

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-feedstock#158]
I think since conda started included the test files in the recipe, the size of this package blew up.

The extracted package is close to 100MB, but only 5MB of the package is actually useful to the end user.

I understand the need to "test" the packages, but 100MB seems a little excessive.

Finally, if you delete the test files from the archive, the file size is reduced from 17MB to 1MB.
![image](https://user-images.githubusercontent.com/90008/150644141-f1dc8e32-6530-42f5-a329-a9af469cf27a.png)

Would it be accetable to create a split package?

I feel like there are a few other packages I want to do this with, but I would like to ask for what people think a good naming convention would be.

Is it:

```
conda-test
```
?

**Comment by hmaarrfk** [comment]
Hmm, it seems that the source test files were never used.

So I'm just suggesting we remove them.
https://github.com/conda-forge/conda-feedstock/pull/159

**Comment by jaimergp** [comment]
+1

I don't understand why it's so heavy though, since the source files shouldn't be included right now? 

https://github.com/conda-forge/conda-feedstock/blob/72c9f40c476d0ecd2cde3854ac2d8bda80235820/recipe/meta.yaml#L62-L66

Isn't `run_pytest` false here? Do we need `False` (uppercase) or, actually, test for equality with `yes` and `no`? I'll put a PR.
